export const members = [
	{
		name: "반님",
		image: "/images/반님.png",
		xUrl: "https://x.com/Van_Nim_",
		chzzkUrl: "https://chzzk.naver.com/3a2d2f4e9132d822423f6aa879e598c5",
		youtubeUrl: "https://www.youtube.com/@%EB%B0%98%EB%8B%98",
		group: "Stardays",
		primaryColor: "#FFD700",
	},
	{
		name: "쿠레나이 나츠키",
		image: "/images/쿠레나이 나츠키.png",
		xUrl: "https://x.com/Kurenai_Natsuki",
		chzzkUrl: "https://chzzk.naver.com/0a2020b09b8cc7f2285b7ae5de2ce4d3",
		youtubeUrl: "https://www.youtube.com/@%EB%82%98%EC%B8%A0%ED%82%A4",
		group: "Stardays",
	},
	{
		name: "테리눈나",
		image: "/images/테리눈나.png",
		xUrl: "https://x.com/Terri_Nunna",
		chzzkUrl: "https://chzzk.naver.com/0a2020b09b8cc7f2285b7ae5de2ce4d3",
		youtubeUrl: "https://www.youtube.com/@%ED%85%8C%EB%A6%AC%EB%88%88%EB%82%98",
		group: "Stardays",
	},
	{
		name: "빙하유",
		image: "/images/빙하유.png",
		xUrl: "https://x.com/binghayu",
		chzzkUrl: "https://chzzk.naver.com/a048127622edd6c3ee8e477471a1d823",
		youtubeUrl: "https://www.youtube.com/@binghayu",
		group: "Luvdia",
	},
	{
		name: "양메이",
		image: "/images/양메이.png",
		xUrl: "https://x.com/yangmei1126",
		chzzkUrl: "https://chzzk.naver.com/f1869f490ddd660c420b2f57c649e6bb",
		youtubeUrl: "https://www.youtube.com/@%EC%96%91%EB%A9%94%EC%9D%B4",
		group: "Luvdia",
	},
	{
		name: "유리리",
		image: "/images/유리리.png",
		xUrl: "https://x.com/U_LiLi__",
		chzzkUrl: "https://chzzk.naver.com/29a1ed5c0829fa620fab900dba7e011b",
		youtubeUrl: "https://www.youtube.com/@U-Lili22",
		group: "Luvdia",
	},
	{
		name: "온하루",
		image: "/images/온하루.png",
		xUrl: "https://x.com/otw_haru",
		chzzkUrl: "https://chzzk.naver.com/0f61ae00c2aef2b789dc009e51cbcc5a",
		youtubeUrl: "https://www.youtube.com/@otw_onharu",
		group: "Hi-Blueming",
	},
	{
		name: "김아테",
		image: "/images/김아테.png",
		xUrl: "https://x.com/otw_ate",
		chzzkUrl: "https://chzzk.naver.com/f42e97f59c3177b8686dccfbf90792dd",
		youtubeUrl: "https://www.youtube.com/@otw_Ate",
		group: "Hi-Blueming",
	},
	{
		name: "하네",
		image: "/images/하네.png",
		xUrl: "https://x.com/otw_hane",
		chzzkUrl: "https://chzzk.naver.com/7b9c6553913c755812ef2cd9fbe1dc5c",
		youtubeUrl: "https://www.youtube.com/@otw_hane",
		group: "Hi-Blueming",
	},
	{
		name: "오토노 소리",
		image: "/images/오토노 소리.png",
		xUrl: "https://x.com/otw_sori",
		chzzkUrl: "https://chzzk.naver.com/2e5c0e7ce8321194127e4d79c83c36d4",
		youtubeUrl: "https://www.youtube.com/@otw_Sori",
		group: "Hi-Blueming",
	},
];
